import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

/// Dev overlay calibrator — draggable/resizable corner squares
/// for tuning marker detection positions.
///
/// Usage:
///   1. Long press settings icon → enter dev mode
///   2. Drag corners to adjust position
///   3. Drag center resize handle up/down to resize
///   4. Tap "Done" → shows code snippet to copy
class DevOverlayCalibrator extends StatefulWidget {
  final Size screenSize;
  final VoidCallback onDone;
  final Function(String code) onCodeGenerated;

  const DevOverlayCalibrator({
    super.key,
    required this.screenSize,
    required this.onDone,
    required this.onCodeGenerated,
  });

  @override
  State<DevOverlayCalibrator> createState() => _DevOverlayCalibratorState();
}

class _DevOverlayCalibratorState extends State<DevOverlayCalibrator> {
  // Corner positions (relative to screen, 0.0-1.0)
  double _tlX = 0.02, _tlY = 0.02;
  double _sqSize = 0.12; // square size as % of screen width

  // Drag state
  int? _draggingCorner; // 0=TL, 1=TR, 2=BL, 3=BR
  Offset _dragStart = Offset.zero;
  Offset _cornerStart = Offset.zero;

  // Resize state
  bool _resizing = false;
  double _resizeStartY = 0;
  double _resizeStartSize = 0;

  // Get corner positions (TL, TR, BL, BR)
  List<Offset> get _corners => [
        Offset(_tlX, _tlY),                           // TL
        Offset(1.0 - _tlX - _sqSize, _tlY),           // TR (mirrored X)
        Offset(_tlX, 1.0 - _tlY - _sqSize),           // BL (mirrored Y)
        Offset(1.0 - _tlX - _sqSize, 1.0 - _tlY - _sqSize), // BR (mirrored both)
      ];

  void _onPanStart(DragStartDetails details, int corner) {
    setState(() {
      _draggingCorner = corner;
      _dragStart = details.localPosition;
      _cornerStart = Offset(_tlX, _tlY);
    });
  }

  void _onPanUpdate(DragUpdateDetails details) {
    if (_draggingCorner == null) return;
    final dx = details.localPosition.dx - _dragStart.dx;
    final dy = details.localPosition.dy - _dragStart.dy;
    final screenW = widget.screenSize.width;
    final screenH = widget.screenSize.height;

    setState(() {
      _tlX = (_cornerStart.dx + dx / screenW).clamp(0.0, 0.5 - _sqSize);
      _tlY = (_cornerStart.dy + dy / screenH).clamp(0.0, 0.5 - _sqSize);
    });
  }

  void _onPanEnd(DragEndDetails details) {
    setState(() {
      _draggingCorner = null;
    });
  }

  // Resize: drag up = bigger, drag down = smaller
  void _onResizeStart(DragStartDetails details) {
    setState(() {
      _resizing = true;
      _resizeStartY = details.localPosition.dy;
      _resizeStartSize = _sqSize;
    });
  }

  void _onResizeUpdate(DragUpdateDetails details) {
    if (!_resizing) return;
    final dy = _resizeStartY - details.localPosition.dy; // up = positive
    final screenH = widget.screenSize.height;
    final delta = dy / screenH * 0.5; // scale factor
    setState(() {
      _sqSize = (_resizeStartSize + delta).clamp(0.05, 0.30);
    });
  }

  void _onResizeEnd(DragEndDetails details) {
    setState(() {
      _resizing = false;
    });
  }

  void _generateCode() {
    final screenW = widget.screenSize.width;
    final screenH = widget.screenSize.height;

    final code = '''
// Dev-calibrated overlay positions
// Screen: ${screenW.round()}x${screenH.round()}
// Generated by DevOverlayCalibrator

// In _AzotaOverlayPainter.paint():
final sqSize = screenW * ${_sqSize.toStringAsFixed(4)};
final marginX = screenW * ${_tlX.toStringAsFixed(4)};
final marginY = screenH * ${_tlY.toStringAsFixed(4)};

final corners = [
  (0, Rect.fromLTWH(marginX, marginY, sqSize, sqSize)),                           // TL
  (1, Rect.fromLTWH(screenW - sqSize - marginX, marginY, sqSize, sqSize)),         // TR
  (2, Rect.fromLTWH(marginX, screenH - sqSize - marginY, sqSize, sqSize)),         // BL
  (3, Rect.fromLTWH(screenW - sqSize - marginX, screenH - sqSize - marginY, sqSize, sqSize)), // BR
];''';

    widget.onCodeGenerated(code);
  }

  @override
  Widget build(BuildContext context) {
    final screenW = widget.screenSize.width;
    final screenH = widget.screenSize.height;
    final sqPx = _sqSize * screenW;

    return Stack(
      children: [
        // Semi-transparent background
        GestureDetector(
          onTap: () {}, // Absorb taps
          child: Container(color: Colors.black.withOpacity(0.3)),
        ),

        // 4 corner squares (draggable)
        for (int i = 0; i < 4; i++)
          Positioned(
            left: _corners[i].dx * screenW,
            top: _corners[i].dy * screenH,
            width: sqPx,
            height: sqPx,
            child: GestureDetector(
              onPanStart: (d) => _onPanStart(d, i),
              onPanUpdate: _onPanUpdate,
              onPanEnd: _onPanEnd,
              child: Container(
                decoration: BoxDecoration(
                  color: _draggingCorner == i
                      ? Colors.yellow.withOpacity(0.5)
                      : Colors.green.withOpacity(0.3),
                  border: Border.all(
                    color: _draggingCorner == i ? Colors.yellow : Colors.green,
                    width: 3,
                  ),
                ),
                child: Center(
                  child: Text(
                    ['TL', 'TR', 'BL', 'BR'][i],
                    style: const TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
              ),
            ),
          ),

        // Resize handle (center, drag up/down)
        Positioned(
          left: screenW / 2 - 40,
          top: screenH / 2 - 40,
          width: 80,
          height: 80,
          child: GestureDetector(
            onPanStart: _onResizeStart,
            onPanUpdate: _onResizeUpdate,
            onPanEnd: _onResizeEnd,
            child: Container(
              decoration: BoxDecoration(
                color: _resizing
                    ? Colors.orange.withOpacity(0.8)
                    : Colors.orange.withOpacity(0.6),
                shape: BoxShape.circle,
                border: Border.all(color: Colors.white, width: 2),
              ),
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const Icon(Icons.swap_vert, color: Colors.white, size: 20),
                  Text(
                    '${(_sqSize * 100).toStringAsFixed(0)}%',
                    style: const TextStyle(color: Colors.white, fontSize: 10),
                  ),
                ],
              ),
            ),
          ),
        ),

        // Info bar
        Positioned(
          top: 40,
          left: 0,
          right: 0,
          child: Container(
            margin: const EdgeInsets.symmetric(horizontal: 16),
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: Colors.black87,
              borderRadius: BorderRadius.circular(8),
            ),
            child: Text(
              'DEV: Drag corners to move. Drag center ↕ to resize.\n'
              'TL↔TR, BL↔BR mirrored. '
              'Size: ${(_sqSize * 100).toStringAsFixed(1)}%  '
              'Margin: ${(_tlX * 100).toStringAsFixed(1)}%x${(_tlY * 100).toStringAsFixed(1)}%',
              style: const TextStyle(color: Colors.white70, fontSize: 10),
              textAlign: TextAlign.center,
            ),
          ),
        ),

        // Done button
        Positioned(
          bottom: 100,
          left: 0,
          right: 0,
          child: Center(
            child: ElevatedButton.icon(
              onPressed: () {
                _generateCode();
                widget.onDone();
              },
              icon: const Icon(Icons.check, size: 20),
              label: const Text('Done — Generate Code'),
              style: ElevatedButton.styleFrom(
                backgroundColor: Colors.green,
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
              ),
            ),
          ),
        ),
      ],
    );
  }
}
