# Generated by Django 6.0.2 on 2026-04-21 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0004_examvariant_submission_variant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_retention_days', models.PositiveIntegerField(choices=[(0, 'Không tự xóa'), (7, 'Sau 7 ngày'), (30, 'Sau 30 ngày'), (90, 'Sau 90 ngày'), (180, 'Sau 6 tháng')], default=30, help_text='Tự động xóa ảnh phiếu đã chấm sau N ngày. 0 = không xóa.', verbose_name='Tự động xóa ảnh cũ (ngày)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cài đặt người dùng',
                'verbose_name_plural': 'Cài đặt người dùng',
            },
        ),
    ]
