# Generated by Django 6.0.2 on 2026-04-21 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0005_usersettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='contribute_training_data',
            field=models.BooleanField(default=False, help_text='Cho phép ứng dụng gửi ảnh phiếu đã chấm (sạch, 100% nhận diện) lên server để cải thiện mô hình nhận dạng.', verbose_name='Góp ảnh để cải thiện AI'),
        ),
        migrations.CreateModel(
            name='TrainingSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='training/%Y/%m/', verbose_name='Ảnh phiếu')),
                ('made', models.CharField(blank=True, default='', max_length=10, verbose_name='Mã đề')),
                ('sbd', models.CharField(blank=True, default='', max_length=20, verbose_name='Số báo danh')),
                ('template_code', models.CharField(blank=True, default='', max_length=30, verbose_name='Mã phiếu')),
                ('answers_json', models.TextField(blank=True, default='', help_text='JSON: {"part1": [...], "part2": {...}, "part3": [...]}', verbose_name='Labels (JSON)')),
                ('confidence', models.FloatField(default=1.0, verbose_name='Độ tự tin')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_samples', to='grading.submission')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_samples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mẫu training',
                'verbose_name_plural': 'Mẫu training',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
